name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://ShashiKanth16:$HF@huggingface.co/spaces/ShashiKanth16/TextSummarizer

      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://ShashiKanth16:$HF@huggingface.co/spaces/ShashiKanth16/TextSummarizer main